spring:
  datasource:
    url: jdbc:postgresql://api.piggy.bank.it:5432/piggy-bank-db
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
      generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true