spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true

    database-platform: org.hibernate.dialect.H2Dialect

piggy_bank:
  features:
    issuer_to_resolve_user: true
    jwt_token_type: true

####### CONSIDERED FOR LOCAL DEVELOPMENT ONLY ########
security:
  keystore:
    location: classpath:piggybank-local.p12
    password: testpwd