spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/piggy_bank
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true