version: '3.1'

services:
  backend:
    build:
      context: .
      args:
        JAR_FILE: piggy-bank-backend.jar
    depends_on:
      - "db"
    environment:
      - SPRING_PROFILES_ACTIVE=production
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: piggy_bank
    ports:
    - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080

